theme: jekyll-theme-minimal
title: Priyajit Biswal — Software Engineer & AI Enthusiast
description: Priyajit's CV, projects, certifications, and professional journey in AI, data science, and software engineering.
